---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp
  become: true
  become_method: su
  become_user: root

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp
  become: true
  become_user: root

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp
  become: true
  become_user: root

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
  become: true
  become_user: root

